services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - my-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=es-password
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - my-network

  movies-api:
    build: ./movies-api
    container_name: movies-api
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017
      - ELASTICSEARCH_URI=http://elasticsearch:9200
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "4000:4000"
    networks:
      - my-network
  
  movies-ui:
    build: ./movies-ui
    container_name: movies-ui
    ports:
      - "3000:80"
    networks:
      - my-network

volumes:
  mongodb_data:
  elasticsearch_data:

networks:
  my-network:
    driver: bridge
